resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: latest

resources:
- name: terraform
  type: terraform
  source:
    env_name: ((terraform_environment_name))
    backend_type: s3
    backend_config:
      bucket: ((environment_state_bucket))
      key: bosh/terraform.tfstate
      region: ((environment_region))
      access_key: ((environment_access_key))
      secret_key: ((environment_secret_key))
    vars:
      tag_name: concourse
    env:
      AWS_ACCESS_KEY_ID: ((environment_access_key))
      AWS_SECRET_ACCESS_KEY: ((environment_secret_key))

- name: source_code
  type: git
  source:
    uri: git@github.com:bosh-rebels/studious-couscous.git
    branch: main
    private_key: ((source_code_rsa.private_key))

jobs:
- name: job
  public: true
  plan:
  - get: source_code
    trigger: true
  - put: terraform
    params:
      terraform_source: source_code/ci/terraform
