resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: latest

resources:
- name: terraform_bosh
  type: terraform
  source:
    env_name: ((terraform_environment_name))
    backend_type: s3
    backend_config:
      bucket: ((environment_state_bucket))
      key: bosh/terraform.tfstate
      region: ((environment_region))
      access_key: ((environment_access_key))
      secret_key: ((environment_secret_key))
    vars:
      tag_name: concourse
      env_region: ((environment_region))
      concourse_public_ip: ((concourse_public_ip))
      env_name: ((terraform_environment_name))
    env:
      AWS_ACCESS_KEY_ID: ((environment_access_key))
      AWS_SECRET_ACCESS_KEY: ((environment_secret_key))

- name: source_code
  type: git
  source:
    uri: git@github.com:bosh-rebels/studious-couscous.git
    branch: main
    private_key: ((source_code_rsa.private_key))

- name: bosh_code
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-deployment
    branch: master

- name: bosh_docker_image
  type: docker-image
  source:
    repository: cloudfoundry/bosh-cli
    tag: 'latest'

jobs:
- name: setup_bosh
  public: true
  plan:
  - get: source_code
    trigger: true
  - get: bosh_code
  - put: terraform_bosh
    params:
      terraform_source: source_code/ci/terraform
  - load_var: terraform_outputs
    file: terraform_bosh/metadata
    format: json
  - task: deploy_bosh
    image: bosh_docker_image
    config:
      platform: linux
      inputs:
        - name: bosh_code
      run:
        path: /bin/bash
        args:
          - -c
          - |
            bosh create-env bosh_code/bosh.yml \
            --state=state.json \
            --vars-store=creds.yml \
            -o bosh_code/aws/cpi.yml \
            -v director_name=bosh-1 \
            -v internal_cidr=10.0.1.0/24 \
            -v internal_gw=10.0.1.1 \
            -v internal_ip=10.0.1.6 \
            -v access_key_id=((environment_access_key)) \
            -v secret_access_key=((environment_secret_key)) \
            -v region=((environment_region)) \
            -v az=eu-west-1a \
            -v default_key_name=((.:terraform_outputs.bosh_private_key_name)) \  ####
            -v default_security_groups=[bosh_private] \
            --var private_key=((.:terraform_outputs.bosh_private_key)) \  ####
            -v subnet_id=((.:terraform_outputs.bosh_private_subnet))

